DB_USERNAME="${MYSQL_USERNAME:-mysql}"
DB_PASSWORD="${MYSQL_PASSWORD:-mysql}"
DB_ROOT_PASSWORD="${MYSQL_ROOT_PASSWORD:-root}"
DB_DBNAME="${MYSQL_DBNAME:-test_db}"
DOCKER_DB_MOUNTPOINT="/var/lib/mysql"
DOCKER_DB_PORT=3306